# Generated by Django 5.1.2 on 2024-11-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="color",
            field=models.TextField(default="black"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productmodel",
            name="description",
            field=models.TextField(default="No description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productmodel",
            name="product_dimensions",
            field=models.TextField(default="No dimensions"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productmodel",
            name="seller",
            field=models.TextField(default="No seller"),
            preserve_default=False,
        ),
    ]
